# Basic Joins

## 1378. Replace Employee ID With The Unique Identifier

In [ ]:
select unique_id, name
from Employees as e
Left Join EmployeeUNI as u
ON e.id = u.id;

## 1068. Product Sales Analysis I

In [ ]:
select product_name, year, price
from Sales as s
Left Join Product as p
ON s.product_id = p.product_id;

## 1581. Customer Who Visited but Did Not Make Any Transactions

In [ ]:
select v.customer_id, count(*) as count_no_trans
from Visits as v
Left Join Transactions as t
ON v.visit_id = t.visit_id
where t.transaction_id is null
group by v.customer_id;

## 197. Rising Temperature

In [ ]:
SELECT w1.id
FROM Weather w1
JOIN Weather w2
WHERE DATEDIFF(w1.recordDate, w2.recordDate) = 1 
AND w2.temperature < w1.temperature;

## 1661. Average Time of Process per Machine

In [ ]:
SELECT a.machine_id, ROUND(AVG(b.timestamp-a.timestamp),3) as processing_time
FROM Activity AS a
LEFT JOIN Activity as b
ON a.machine_id = b.machine_id AND a.process_id = b.process_id AND a.activity_type ='start' and b.activity_type = 'end'
GROUP BY a.machine_id;

## 577. Employee Bonus

In [ ]:
SELECT e.name, b.bonus
from Employee as e
Left join Bonus as b
On e.empId = b.empId
where bonus < 1000 or bonus is null;

## 1280. Students and Examinations

In [ ]:
SELECT s.student_id, s.student_name, u.subject_name, count(e.student_id) as attended_exams
FROM Students as s  
CROSS JOIN Subjects as u
LEFT JOIN Examinations as e
ON s.student_id = e.student_id AND u.subject_name = e.subject_name
GROUP BY s.student_id, s.student_name, u.subject_name
ORDER BY s.student_id, u.subject_name;

## 570. Managers with at Least 5 Direct Reports

In [ ]:
SELECT b.name
FROM Employee AS a
INNER JOIN Employee as b
ON  b.id = a.managerId
group by b.id
having count(*) >= 5;

## 1934. Confirmation Rate

In [ ]:
SELECT s.user_id, IFNULL(ROUND(AVG(c.action = 'confirmed'), 2), 0) AS confirmation_rate
FROM Signups AS s
LEFT JOIN Confirmations as c
USING (user_id)
GROUP BY s.user_id;